// Feature: pc-unlock
// PairingHandlerTests — unit tests for PairingHandler.
// Requirements: 6.1, 6.2, 6.5, 6.6, 10.2

using Microsoft.Extensions.Logging.Abstractions;
using PCUnlockService.Pairing;
using Xunit;

namespace PCUnlockService.Tests.Pairing;

/// <summary>
/// Unit tests for <see cref="PairingHandler"/> using a mock
/// <see cref="IBLEPairingChannel"/> so no real BLE hardware is required.
/// </summary>
public sealed class PairingHandlerTests
{
    // -------------------------------------------------------------------------
    // Helpers / stubs
    // -------------------------------------------------------------------------

    /// <summary>
    /// Stub BLE channel whose behaviour is controlled per-test.
    /// </summary>
    private sealed class StubBLEPairingChannel : IBLEPairingChannel
    {
        private readonly PairingRequest? _response;
        private readonly TimeSpan _delay;

        /// <param name="response">
        ///   The <see cref="PairingRequest"/> to return, or <c>null</c> to
        ///   simulate a timeout (waits until the token is cancelled).
        /// </param>
        /// <param name="delay">Optional artificial delay before returning.</param>
        public StubBLEPairingChannel(PairingRequest? response, TimeSpan delay = default)
        {
            _response = response;
            _delay    = delay;
        }

        public async Task<PairingRequest?> AwaitPairingRequestAsync(CancellationToken ct)
        {
            if (_response is null)
            {
                // Simulate a channel that never receives a request —
                // block until the token fires, then return null.
                try
                {
                    await Task.Delay(Timeout.InfiniteTimeSpan, ct).ConfigureAwait(false);
                }
                catch (OperationCanceledException)
                {
                    // Expected — the caller's timeout fired.
                }
                return null;
            }

            if (_delay > TimeSpan.Zero)
            {
                await Task.Delay(_delay, ct).ConfigureAwait(false);
            }

            return _response;
        }

        public Task SendPairingCompleteAsync(CancellationToken ct)
            => Task.CompletedTask;
    }

    /// <summary>
    /// Captures the pairing code generated by <see cref="PairingHandler"/> so
    /// the test can echo it back correctly.
    ///
    /// Implementation: we intercept <see cref="IBLEPairingChannel.AwaitPairingRequestAsync"/>
    /// on the first call — by that point the handler has already logged the
    /// payload JSON containing the code, but we need to capture it differently.
    ///
    /// Instead, this helper runs <see cref="PairingHandler"/> with a channel
    /// that reads the code from the log-captured payload JSON; however, since
    /// <see cref="NullLogger{T}"/> discards output, the simplest approach is a
    /// two-pass channel: the first <c>AwaitPairingRequestAsync</c> call signals
    /// a <see cref="TaskCompletionSource{T}"/> that the handler has committed
    /// to a code, then we inspect state to build the echo.
    ///
    /// For test purposes we use a simpler, self-contained approach: create a
    /// custom channel that receives the correct code via a shared callback.
    /// </summary>
    private sealed class CodeCapturingBLEChannel : IBLEPairingChannel
    {
        private readonly TaskCompletionSource<string> _codeTcs = new();

        /// <summary>Called by the test after capturing the code from the handler.</summary>
        public Task<string> CodeTask => _codeTcs.Task;

        public async Task<PairingRequest?> AwaitPairingRequestAsync(CancellationToken ct)
        {
            // Wait until the test has provided us with the correct pairing code
            // to echo back.  This synchronises with the test harness below.
            string code = await _codeTcs.Task.WaitAsync(ct).ConfigureAwait(false);

            return new PairingRequest
            {
                PublicKeyDER    = new byte[] { 0x04, 0xAB, 0xCD }, // minimal stub public key
                PairingCodeEcho = code,
            };
        }

        public Task SendPairingCompleteAsync(CancellationToken ct)
            => Task.CompletedTask;

        /// <summary>Provides the pairing code to echo back.</summary>
        public void ProvideCode(string code) => _codeTcs.TrySetResult(code);
    }

    // -------------------------------------------------------------------------
    // Test: correct code → Success + DeviceRecord populated
    // -------------------------------------------------------------------------

    [Fact]
    public async Task StartPairingAsync_CorrectCode_ReturnsSuccess_WithDeviceRecord()
    {
        // Arrange
        // We need to know the generated code to echo it back.
        // We do this by creating a channel that cooperates with the test:
        // the handler generates the code, and before awaiting the BLE write we
        // arrange to have the correct code echoed.  Since the handler generates
        // the code *before* calling AwaitPairingRequestAsync, and our stub
        // blocks on _codeTcs, we drive the test from outside using a
        // CaptureChannel + a logger shim.
        //
        // Simpler alternative (used here): wrap the real handler in a subclass
        // is not possible (sealed class).  Instead, we use a channel stub that
        // accepts *any* code (correct by construction) by making the stub
        // deterministic about what it returns.
        //
        // The cleanest approach without modifying PairingHandler: run the
        // handler on a background task, capture the pairing code from the
        // payload via a logging shim.  For simplicity in tests we use the
        // following pattern: the test channel itself generates the correct echo
        // by being pre-seeded with the same alphabet call (impossible without
        // intercepting).
        //
        // Therefore, we use a RecordingLogger that captures log messages and a
        // coordination channel.

        var logger  = new RecordingLogger<PairingHandler>();
        var channel = new CodeCapturingBLEChannel();
        var handler = new PairingHandler(channel, logger);

        const string DeviceName = "Test iPhone";
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));

        // Act — start the pairing on a background task so we can intercept the
        // log message that contains the payload JSON, extract the code, and
        // feed it back to the channel.
        var pairingTask = handler.StartPairingAsync(DeviceName, cts.Token);

        // Wait until the handler logs the payload JSON (which contains the code).
        string? pairingCode = await WaitForPairingCodeFromLogger(logger, cts.Token);
        Assert.NotNull(pairingCode);

        // Provide the captured code to the channel so it echoes correctly.
        channel.ProvideCode(pairingCode!);

        PairingResult result = await pairingTask;

        // Assert
        Assert.Equal(PairingOutcome.Success, result.Outcome);
        Assert.NotNull(result.Device);
        Assert.Equal(DeviceName, result.Device!.DeviceName);
        Assert.NotEqual(Guid.Empty, result.Device.DeviceId);
        Assert.NotEmpty(result.Device.PublicKeyDER);
        Assert.Equal(16, result.Device.PcIdentityToken.Length);
        Assert.True(result.Device.PairedAt <= DateTimeOffset.UtcNow);
        Assert.Null(result.Device.LastUsedAt);
    }

    // -------------------------------------------------------------------------
    // Test: external cancellation → Cancelled result, no device record
    // (covers the same "no response received → session state cleared" path as
    //  a 120-second timeout, but completes fast by cancelling the external token)
    // -------------------------------------------------------------------------

    [Fact]
    public async Task StartPairingAsync_Timeout_ReturnsTimeout_SessionStateCleared()
    {
        // Arrange — channel that never responds (blocks until the CT fires).
        var channel = new StubBLEPairingChannel(response: null);
        var handler = new PairingHandler(channel, NullLogger<PairingHandler>.Instance);

        // Cancel the external token quickly so the test doesn't wait 120s.
        // The handler's internal 120s CTS and the external CTS are linked;
        // whichever fires first unblocks the channel.  When the external CT
        // fires, PairingHandler returns Cancelled.  When the internal 120s
        // timer fires first (with CancellationToken.None), it returns Timeout.
        // Both code paths clear session state.  We exercise the Cancelled path
        // here for speed; the logic that clears state is identical for both.
        using var cts = new CancellationTokenSource(TimeSpan.FromMilliseconds(50));

        PairingResult result = await handler.StartPairingAsync("Test iPhone", cts.Token);

        // Assert — Cancelled (external token fired) or Timeout (internal timer fired).
        // Either way: not Success, and Device must be null (session state cleared).
        Assert.True(
            result.Outcome == PairingOutcome.Cancelled || result.Outcome == PairingOutcome.Timeout,
            $"Expected Cancelled or Timeout, got {result.Outcome}");
        Assert.Null(result.Device);
    }

    // -------------------------------------------------------------------------
    // Test: code mismatch → CodeMismatch result, no device record
    // -------------------------------------------------------------------------

    [Fact]
    public async Task StartPairingAsync_CodeMismatch_ReturnsCodeMismatch_SessionStateCleared()
    {
        // Arrange — channel returns a request with a deliberately wrong code.
        var wrongRequest = new PairingRequest
        {
            PublicKeyDER    = new byte[] { 0x04, 0xDE, 0xAD, 0xBE, 0xEF },
            PairingCodeEcho = "ZZZZZZ", // will never match the generated code
        };
        var channel = new StubBLEPairingChannel(wrongRequest);
        var handler = new PairingHandler(channel, NullLogger<PairingHandler>.Instance);

        // Act
        PairingResult result = await handler.StartPairingAsync(
            "Rogue iPhone",
            CancellationToken.None);

        // Assert
        Assert.Equal(PairingOutcome.CodeMismatch, result.Outcome);
        Assert.Null(result.Device);
    }

    // -------------------------------------------------------------------------
    // Helpers — RecordingLogger + pairing-code extraction
    // -------------------------------------------------------------------------

    /// <summary>
    /// Polls the recording logger until it captures the log message that
    /// contains the pairing payload JSON, then extracts the "code" field.
    /// </summary>
    private static async Task<string?> WaitForPairingCodeFromLogger(
        RecordingLogger<PairingHandler> logger,
        CancellationToken ct)
    {
        const int PollMs = 10;
        const int MaxWaitMs = 5_000;
        int elapsed = 0;

        while (elapsed < MaxWaitMs)
        {
            foreach (string msg in logger.Messages)
            {
                // The handler logs: "... PairingPayload JSON: { ... "code":"XXXXXX" ... }"
                int codeIdx = msg.IndexOf("\"code\":", StringComparison.Ordinal);
                if (codeIdx >= 0)
                {
                    // Extract the 6-char code value from the JSON snippet.
                    int start = msg.IndexOf('"', codeIdx + 7);
                    if (start >= 0)
                    {
                        int end = msg.IndexOf('"', start + 1);
                        if (end > start)
                        {
                            return msg.Substring(start + 1, end - start - 1);
                        }
                    }
                }
            }

            await Task.Delay(PollMs, ct).ConfigureAwait(false);
            elapsed += PollMs;
        }

        return null;
    }
}

// ---------------------------------------------------------------------------
// RecordingLogger — captures log messages for assertion in tests
// ---------------------------------------------------------------------------

/// <summary>
/// Simple <see cref="Microsoft.Extensions.Logging.ILogger{T}"/> implementation
/// that stores formatted log messages in a thread-safe list so tests can
/// inspect them.
/// </summary>
internal sealed class RecordingLogger<T> : Microsoft.Extensions.Logging.ILogger<T>
{
    private readonly System.Collections.Concurrent.ConcurrentBag<string> _messages = new();

    /// <summary>All messages logged so far.</summary>
    public IEnumerable<string> Messages => _messages;

    public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

    public bool IsEnabled(Microsoft.Extensions.Logging.LogLevel logLevel) => true;

    public void Log<TState>(
        Microsoft.Extensions.Logging.LogLevel logLevel,
        Microsoft.Extensions.Logging.EventId eventId,
        TState state,
        Exception? exception,
        Func<TState, Exception?, string> formatter)
    {
        _messages.Add(formatter(state, exception));
    }
}
